/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zstd_hangl_zstdtest_mathutil_MathUtil */

#ifndef _Included_com_zstd_hangl_zstdtest_mathutil_MathUtil
#define _Included_com_zstd_hangl_zstdtest_mathutil_MathUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zstd_hangl_zstdtest_mathutil_MathUtil
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zstd_hangl_zstdtest_mathutil_MathUtil_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zstd_hangl_zstdtest_mathutil_MathUtil
 * Method:    reduce
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zstd_hangl_zstdtest_mathutil_MathUtil_reduce
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
